language: node_js
node_js:
  - "8"
cache:
  directories:
  - node_modules
script:
  - yarn test -- --coverage # Include coverage when running tests
  - yarn build
after_script: # Upload coverage reports 
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
deploy:
  skip_cleanup: true
  provider: firebase
  token: $firebase_token