language: node_js
node_js:
  - "10"
notifications:
  webhooks: https://www.travisbuddy.com/
jobs:
  include:
    - stage: install
      script: npm ci
    - stage: test
      script: npm run coverage
    - stage: build
      script: npm run build
    - stage: deploy
      deploy:
        skip_cleanup: true
        provider: firebase
        token: $firebase_token
stages:
  - install
  - test
  - name: build
  - name: deploy
    if: branch = master
