language: node_js
node_js:
  - "8"
notifications:
  webhooks: https://www.travisbuddy.com/
cache:
  directories:
  - node_modules
jobs:
  include:
    - stage: test
      script: yarn coverage
    - stage: build
      script: yarn build
    - stage: deploy
      deploy:
        skip_cleanup: true
        provider: firebase
        token: $firebase_token
stages:
  - test
  - name: build
  - name: deploy
    if: branch = master
